Repository GSG-FC03/TODO-List-team-2, pull requests merged in 2021-07, with the labels that each got.

#5 update files strcture
  assets‏/add.svg
  assets‏/alarmclock.svg
  assets‏/arrow.svg
  assets‏/close.svg
  assets‏/dark.svg
  assets‏/filter.svg
  assets‏/grid.svg
  assets‏/light.svg
  assets‏/list.svg
  assets‏/onboarding.svg
  assets‏/trash.svg
  assets‏/welcome.svg
  css/addnode.css
  css/onboarding‏.css
  css/style.css
  css/todo.js
  index.html
Labels: done

#10 create on boarding
  css/onboarding‏.css
  index.html
Labels: done

#12 fix title and link html with css
  index.html
Labels: done

#13 create home page htmlAndCss >relates#6
  css/style.css
  index.html
Labels: done

#14 create add note
  css/addnode.css
  index.html
Labels: waiting review

#22 Create function Dark And light mode
  css/style.css
  index.html
  todo.js
Labels: waiting review

#24 functions for on boarding page
  todo.js
Labels: done

#25 open&close add task page
  index.html
  todo.js
Labels: waiting review

#26 19 functions for create task
  todo.js
Labels: waiting review

#32 functions for add label >relates#18
  todo.js
Labels: waiting review

#35 show update task
  todo.js
Labels: waiting review

#36 function for delete task from local storage
  todo.js
Labels: waiting review

#37 function for cheackAndUnCeack
  README.md
  todo.js
Labels: waiting review

#38 create function custom-select-function
  todo.js
Labels: waiting review

#39 function for no task message
  todo.js
Labels: done, waiting review

#40 create loadTasks function >relates#29
  todo.js
Labels: done

#42 41 modify format date and time
  todo.js
Labels: waiting review

#43 responsive style for all pages
  css/addnode.css
  css/onboarding‏.css
  css/style.css
Labels: done

#44 function for input certain date or time in add task page
  todo.js
Labels: done

#46 sort and filter functions
  todo.js
Labels: waiting review

#47 modify and format the index.html
  index.html
Labels: waiting review

#51 write readme file and modify in
  README.md
Labels: waiting review

#48 modify and format css files
  css/addnode.css
  css/onboarding‏.css
  css/style.css
Labels: waiting review

#50 solve the error >relates#49
  todo.js
Labels: waiting review

#53 1 add livelink in readme file
  README.md
Labels: waiting review

#54 52 modigy links
  css/style.css
  index.html
  todo.js
Labels: waiting review

#56 modifyLinks >relates#55
  index.html
  todo.js
Labels: waiting review
